---
framework: mocha     
preRun:
  command:
    - npm ci          
postMerge:
  pattern: 
#     - "./test/*.js"
    - "./test/*/*.js"
preMerge:
  pattern:
#     - "./test/*.js"
    - "./test/*/*.js"
postRun:
  command:
    - node --version
version: 1.0
