---
framework: "mocha"
postMerge:
  pattern:
    - "./test/*.js"
    - "./test/*/*.js"
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/*/*.js"
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
